# SonarCloud configuration for user-auth-service
sonar.projectKey=ChirathiSomadasa_Online-Learning-Platform
sonar.organization=chirathisomadasa
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/tests/**,**/coverage/**
sonar.host.url=https://sonarcloud.io
sonar.javascript.lcov.reportPaths=coverage/lcov.info